### ISSUE TITLE
what is missing from this code?

### ISSUE THREAD

**Issue by 69kevinutah69** [DragonQuestHero/PUBG-PAK-Hacker#1]
you said there is complete code that you cant give so what is missing in this version

**Comment by DragonQuestHero** [comment]
miss MiProcessLoaderEntry function address
using that to hidden driver on kernel mode
if u application just running of win7x64
u can use this project code https://github.com/Sqdwr/HideDriver
or this
https://github.com/ZhuHuiBeiShaDiao/NewHideDriverEx
but.i dont suer NewHideDriverEx work on win10.maybe?maybe not

**Comment by DragonQuestHero** [comment]
if u have any question.reopen issuse

**Comment by KlerrUC** [comment]
is this code compile & start ready?

**Comment by DragonQuestHero** [comment]
@KlerrUC compile before.but doesnt work now.
readying upload new code
